return {
  { "DanilaMihailov/beacon.nvim", enabled = false },
  { "ray-x/lsp_signature.nvim", enabled = true },
  { "chikko80/error-lens.nvim", enabled = true },
  { "jay-babu/mason-nvim-dap.nvim", enabled = true },
  { "nvim-lualine/lualine.nvim", enabled = true },
  { "folke/which-key.nvim", enabled = true },
  { "windwp/nvim-ts-autotag", enabled = true },
  { "chikko80/error-lens.nvim", enabled = true },
  { "folke/neodev.nvim", enabled = true },
  { "max397574/colortils.nvim", enabled = false },
  { "j-hui/fidget.nvim", enabled = true },
  { "airblade/vim-gitgutter", enabled = false },
  { "tzachar/cmp-tabnine", enabled = false },
}
